### ISSUE TITLE
MVP checklist

### ISSUE THREAD

**Issue by pepopowitz** [artsy/relay-workshop#22]
This is a checklist for things to complete before pointing new engineers at these exercises for their onboarding.

- [x] #19 Update docs links (addressed in #23)
- [x] #20 Confirm we're using the correct names (addressed in #24)
- [x] #21 Review setup/intro docs (addressed in #25)
- [x] Add a link to onboarding docs
